# Generated by Django 5.1.6 on 2025-03-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password_instance',
        ),
    ]
